version: '3'

services:
  maria:
    image: maria-custom
    container_name: cmaria960
    ports:
      - "960:3306"
    volumes:
      - "${APPDATA}/share/db960/:/var/lib/mysql"
    environment:
      - MARIADB_DATABASE=dbbase
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=123456
      - MARIADB_ROOT_PASSWORD=123456
    networks:
      - lab3-network
networks:
  lab3-network:
    external:
      name: red21
