version: '3'

services:
  web:
    build:
      context: .
      # Nombre de tu Dockerfile, si está en otra ubicación ajusta el path
      dockerfile: Dockerfile
    # El nombre y etiqueta que quieras dar a la imagen
    image: my-web-app:latest
    ports:
      # Mapea el puerto 80 del host al puerto 1337 del contenedor
      - "80:1337"
    volumes:
      # Monta el directorio 'app' en el host al '/app' en el contenedor, si necesitas montar datos o configuraciones
      - ./app:/app
    # Reinicia el contenedor si este se cae
    restart: always
